import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private currentLanguage = new BehaviorSubject<string>('en');
  currentLanguage$ = this.currentLanguage.asObservable();

  private translations: any = {
    en: {
      settings: 'Settings',
      managePreferences: 'Manage your app preferences',
      edit: 'Edit',
      preferences: 'Preferences',
      language: 'Language',
      notifications: 'Notifications',
      lowStockThreshold: 'Low Stock Threshold',
      items: 'items',
      integrationsExport: 'Integrations & Export',
      tallyExport: 'Tally Export Settings',
      autoBackup: 'Auto-Backup to Cloud',
      other: 'Other',
      helpSupport: 'Help & Support',
      logOut: 'Log Out',
      home: 'Home',
      inventory: 'Inventory',
      reports: 'Reports',
      editProfile: 'Edit Profile',
      fullName: 'Full Name',
      shopName: 'Shop Name',
      businessType: 'Business Type',
      cancel: 'Cancel',
      save: 'Save',
      selectLanguage: 'Select Language',
      chooseLanguage: 'Choose your preferred language',
      emailSupport: 'Email Support',
      phoneSupport: 'Phone Support',
      whatsapp: 'WhatsApp',
      documentation: 'Documentation',
      visitHelpCenter: 'Visit our help center',
      close: 'Close',
      enterFullName: 'Enter your full name',
      enterShopName: 'Enter shop name',
      enterBusinessType: 'e.g., Retail, Wholesale, Restaurant'
    },
    hi: {
      settings: 'सेटिंग्स',
      managePreferences: 'अपनी ऐप प्राथमिकताएं प्रबंधित करें',
      edit: 'संपादित करें',
      preferences: 'प्राथमिकताएं',
      language: 'भाषा',
      notifications: 'सूचनाएं',
      lowStockThreshold: 'कम स्टॉक सीमा',
      items: 'आइटम',
      integrationsExport: 'एकीकरण और निर्यात',
      tallyExport: 'टैली निर्यात सेटिंग्स',
      autoBackup: 'क्लाउड पर ऑटो-बैकअप',
      other: 'अन्य',
      helpSupport: 'सहायता और समर्थन',
      logOut: 'लॉग आउट',
      home: 'होम',
      inventory: 'इन्वेंटरी',
      reports: 'रिपोर्ट',
      editProfile: 'प्रोफ़ाइल संपादित करें',
      fullName: 'पूरा नाम',
      shopName: 'दुकान का नाम',
      businessType: 'व्यवसाय का प्रकार',
      cancel: 'रद्द करें',
      save: 'सहेजें',
      selectLanguage: 'भाषा चुनें',
      chooseLanguage: 'अपनी पसंदीदा भाषा चुनें',
      emailSupport: 'ईमेल सहायता',
      phoneSupport: 'फोन सहायता',
      whatsapp: 'व्हाट्सएप',
      documentation: 'दस्तावेज़ीकरण',
      visitHelpCenter: 'हमारे सहायता केंद्र पर जाएं',
      close: 'बंद करें',
      enterFullName: 'अपना पूरा नाम दर्ज करें',
      enterShopName: 'दुकान का नाम दर्ज करें',
      enterBusinessType: 'जैसे, खुदरा, थोक, रेस्तरां'
    },
    mr: {
      settings: 'सेटिंग्ज',
      managePreferences: 'तुमच्या अॅप प्राधान्ये व्यवस्थापित करा',
      edit: 'संपादित करा',
      preferences: 'प्राधान्ये',
      language: 'भाषा',
      notifications: 'सूचना',
      lowStockThreshold: 'कमी स्टॉक मर्यादा',
      items: 'वस्तू',
      integrationsExport: 'एकत्रीकरण आणि निर्यात',
      tallyExport: 'टॅली निर्यात सेटिंग्ज',
      autoBackup: 'क्लाउडवर ऑटो-बॅकअप',
      other: 'इतर',
      helpSupport: 'मदत आणि समर्थन',
      logOut: 'लॉग आउट',
      home: 'होम',
      inventory: 'इन्व्हेंटरी',
      reports: 'अहवाल',
      editProfile: 'प्रोफाइल संपादित करा',
      fullName: 'पूर्ण नाव',
      shopName: 'दुकानाचे नाव',
      businessType: 'व्यवसायाचा प्रकार',
      cancel: 'रद्द करा',
      save: 'जतन करा',
      selectLanguage: 'भाषा निवडा',
      chooseLanguage: 'तुमची पसंतीची भाषा निवडा',
      emailSupport: 'ईमेल समर्थन',
      phoneSupport: 'फोन समर्थन',
      whatsapp: 'व्हाट्सअॅप',
      documentation: 'दस्तऐवजीकरण',
      visitHelpCenter: 'आमच्या मदत केंद्रावर भेट द्या',
      close: 'बंद करा',
      enterFullName: 'तुमचे पूर्ण नाव प्रविष्ट करा',
      enterShopName: 'दुकानाचे नाव प्रविष्ट करा',
      enterBusinessType: 'उदा., किरकोळ, घाऊक, रेस्टॉरंट'
    },
    gu: {
      settings: 'સેટિંગ્સ',
      managePreferences: 'તમારી એપ પસંદગીઓ મેનેજ કરો',
      edit: 'સંપાદિત કરો',
      preferences: 'પસંદગીઓ',
      language: 'ભાષા',
      notifications: 'સૂચનાઓ',
      lowStockThreshold: 'ઓછા સ્ટોકની મર્યાદા',
      items: 'વસ્તુઓ',
      integrationsExport: 'એકીકરણ અને નિકાસ',
      tallyExport: 'ટેલી નિકાસ સેટિંગ્સ',
      autoBackup: 'ક્લાઉડ પર ઓટો-બેકઅપ',
      other: 'અન્ય',
      helpSupport: 'મદદ અને સપોર્ટ',
      logOut: 'લૉગ આઉટ',
      home: 'હોમ',
      inventory: 'ઇન્વેન્ટરી',
      reports: 'રિપોર્ટ્સ',
      editProfile: 'પ્રોફાઇલ સંપાદિત કરો',
      fullName: 'પૂરું નામ',
      shopName: 'દુકાનનું નામ',
      businessType: 'વ્યવસાયનો પ્રકાર',
      cancel: 'રદ કરો',
      save: 'સાચવો',
      selectLanguage: 'ભાષા પસંદ કરો',
      chooseLanguage: 'તમારી પસંદગીની ભાષા પસંદ કરો',
      emailSupport: 'ઇમેઇલ સપોર્ટ',
      phoneSupport: 'ફોન સપોર્ટ',
      whatsapp: 'વોટ્સએપ',
      documentation: 'દસ્તાવેજીકરણ',
      visitHelpCenter: 'અમારા મદદ કેન્દ્રની મુલાકાત લો',
      close: 'બંધ કરો',
      enterFullName: 'તમારું પૂરું નામ દાખલ કરો',
      enterShopName: 'દુકાનનું નામ દાખલ કરો',
      enterBusinessType: 'દા.ત., રિટેલ, હોલસેલ, રેસ્ટોરન્ટ'
    },
    ta: {
      settings: 'அமைப்புகள்',
      managePreferences: 'உங்கள் பயன்பாட்டு விருப்பங்களை நிர்வகிக்கவும்',
      edit: 'திருத்து',
      preferences: 'விருப்பங்கள்',
      language: 'மொழி',
      notifications: 'அறிவிப்புகள்',
      lowStockThreshold: 'குறைந்த இருப்பு வரம்பு',
      items: 'பொருட்கள்',
      integrationsExport: 'ஒருங்கிணைப்பு மற்றும் ஏற்றுமதி',
      tallyExport: 'டேலி ஏற்றுமதி அமைப்புகள்',
      autoBackup: 'கிளவுடில் தானியங்கி காப்புப்பிரதி',
      other: 'மற்றவை',
      helpSupport: 'உதவி மற்றும் ஆதரவு',
      logOut: 'வெளியேறு',
      home: 'முகப்பு',
      inventory: 'சரக்கு',
      reports: 'அறிக்கைகள்',
      editProfile: 'சுயவிவரத்தைத் திருத்து',
      fullName: 'முழு பெயர்',
      shopName: 'கடை பெயர்',
      businessType: 'வணிக வகை',
      cancel: 'ரத்து செய்',
      save: 'சேமி',
      selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
      chooseLanguage: 'உங்கள் விருப்ப மொழியைத் தேர்ந்தெடுக்கவும்',
      emailSupport: 'மின்னஞ்சல் ஆதரவு',
      phoneSupport: 'தொலைபேசி ஆதரவு',
      whatsapp: 'வாட்ஸ்அப்',
      documentation: 'ஆவணங்கள்',
      visitHelpCenter: 'எங்கள் உதவி மையத்தைப் பார்வையிடவும்',
      close: 'மூடு',
      enterFullName: 'உங்கள் முழு பெயரை உள்ளிடவும்',
      enterShopName: 'கடை பெயரை உள்ளிடவும்',
      enterBusinessType: 'எ.கா., சில்லறை, மொத்த, உணவகம்'
    },
    te: {
      settings: 'సెట్టింగ్‌లు',
      managePreferences: 'మీ యాప్ ప్రాధాన్యతలను నిర్వహించండి',
      edit: 'సవరించు',
      preferences: 'ప్రాధాన్యతలు',
      language: 'భాష',
      notifications: 'నోటిఫికేషన్‌లు',
      lowStockThreshold: 'తక్కువ స్టాక్ పరిమితి',
      items: 'వస్తువులు',
      integrationsExport: 'ఏకీకరణలు & ఎగుమతి',
      tallyExport: 'టాలీ ఎగుమతి సెట్టింగ్‌లు',
      autoBackup: 'క్లౌడ్‌కు ఆటో-బ్యాకప్',
      other: 'ఇతర',
      helpSupport: 'సహాయం & మద్దతు',
      logOut: 'లాగ్ అవుట్',
      home: 'హోమ్',
      inventory: 'ఇన్వెంటరీ',
      reports: 'నివేదికలు',
      editProfile: 'ప్రొఫైల్ సవరించు',
      fullName: 'పూర్తి పేరు',
      shopName: 'దుకాణం పేరు',
      businessType: 'వ్యాపార రకం',
      cancel: 'రద్దు చేయి',
      save: 'సేవ్ చేయి',
      selectLanguage: 'భాషను ఎంచుకోండి',
      chooseLanguage: 'మీ ఇష్టమైన భాషను ఎంచుకోండి',
      emailSupport: 'ఇమెయిల్ మద్దతు',
      phoneSupport: 'ఫోన్ మద్దతు',
      whatsapp: 'వాట్సాప్',
      documentation: 'డాక్యుమెంటేషన్',
      visitHelpCenter: 'మా సహాయ కేంద్రాన్ని సందర్శించండి',
      close: 'మూసివేయి',
      enterFullName: 'మీ పూర్తి పేరును నమోదు చేయండి',
      enterShopName: 'దుకాణం పేరును నమోదు చేయండి',
      enterBusinessType: 'ఉదా., రిటైల్, హోల్‌సేల్, రెస్టారెంట్'
    },
    bn: {
      settings: 'সেটিংস',
      managePreferences: 'আপনার অ্যাপ পছন্দগুলি পরিচালনা করুন',
      edit: 'সম্পাদনা',
      preferences: 'পছন্দসমূহ',
      language: 'ভাষা',
      notifications: 'বিজ্ঞপ্তি',
      lowStockThreshold: 'কম স্টক সীমা',
      items: 'আইটেম',
      integrationsExport: 'একীকরণ এবং রপ্তানি',
      tallyExport: 'ট্যালি রপ্তানি সেটিংস',
      autoBackup: 'ক্লাউডে অটো-ব্যাকআপ',
      other: 'অন্যান্য',
      helpSupport: 'সাহায্য এবং সহায়তা',
      logOut: 'লগ আউট',
      home: 'হোম',
      inventory: 'ইনভেন্টরি',
      reports: 'রিপোর্ট',
      editProfile: 'প্রোফাইল সম্পাদনা করুন',
      fullName: 'পুরো নাম',
      shopName: 'দোকানের নাম',
      businessType: 'ব্যবসার ধরন',
      cancel: 'বাতিল',
      save: 'সংরক্ষণ',
      selectLanguage: 'ভাষা নির্বাচন করুন',
      chooseLanguage: 'আপনার পছন্দের ভাষা নির্বাচন করুন',
      emailSupport: 'ইমেল সহায়তা',
      phoneSupport: 'ফোন সহায়তা',
      whatsapp: 'হোয়াটসঅ্যাপ',
      documentation: 'ডকুমেন্টেশন',
      visitHelpCenter: 'আমাদের সহায়তা কেন্দ্র পরিদর্শন করুন',
      close: 'বন্ধ করুন',
      enterFullName: 'আপনার পুরো নাম লিখুন',
      enterShopName: 'দোকানের নাম লিখুন',
      enterBusinessType: 'যেমন, খুচরা, পাইকারি, রেস্তোরাঁ'
    },
    kn: {
      settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      managePreferences: 'ನಿಮ್ಮ ಅಪ್ಲಿಕೇಶನ್ ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
      edit: 'ಸಂಪಾದಿಸಿ',
      preferences: 'ಆದ್ಯತೆಗಳು',
      language: 'ಭಾಷೆ',
      notifications: 'ಅಧಿಸೂಚನೆಗಳು',
      lowStockThreshold: 'ಕಡಿಮೆ ಸ್ಟಾಕ್ ಮಿತಿ',
      items: 'ವಸ್ತುಗಳು',
      integrationsExport: 'ಏಕೀಕರಣಗಳು ಮತ್ತು ರಫ್ತು',
      tallyExport: 'ಟ್ಯಾಲಿ ರಫ್ತು ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      autoBackup: 'ಕ್ಲೌಡ್‌ಗೆ ಸ್ವಯಂ-ಬ್ಯಾಕಪ್',
      other: 'ಇತರೆ',
      helpSupport: 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
      logOut: 'ಲಾಗ್ ಔಟ್',
      home: 'ಹೋಮ್',
      inventory: 'ದಾಸ್ತಾನು',
      reports: 'ವರದಿಗಳು',
      editProfile: 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
      fullName: 'ಪೂರ್ಣ ಹೆಸರು',
      shopName: 'ಅಂಗಡಿಯ ಹೆಸರು',
      businessType: 'ವ್ಯಾಪಾರದ ಪ್ರಕಾರ',
      cancel: 'ರದ್ದುಮಾಡಿ',
      save: 'ಉಳಿಸಿ',
      selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      chooseLanguage: 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      emailSupport: 'ಇಮೇಲ್ ಬೆಂಬಲ',
      phoneSupport: 'ಫೋನ್ ಬೆಂಬಲ',
      whatsapp: 'ವಾಟ್ಸಾಪ್',
      documentation: 'ದಾಖಲಾತಿ',
      visitHelpCenter: 'ನಮ್ಮ ಸಹಾಯ ಕೇಂದ್ರಕ್ಕೆ ಭೇಟಿ ನೀಡಿ',
      close: 'ಮುಚ್ಚಿ',
      enterFullName: 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
      enterShopName: 'ಅಂಗಡಿಯ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
      enterBusinessType: 'ಉದಾ., ಚಿಲ್ಲರೆ, ಸಗಟು, ರೆಸ್ಟೋರೆಂಟ್'
    }
  };

  constructor() {
    const saved = localStorage.getItem('selectedLanguage');
    if (saved) {
      this.currentLanguage.next(saved);
    }
  }

  setLanguage(lang: string) {
    this.currentLanguage.next(lang);
    localStorage.setItem('selectedLanguage', lang);
  }

  translate(key: string): string {
    const lang = this.currentLanguage.value;
    return this.translations[lang]?.[key] || this.translations['en'][key] || key;
  }

  getCurrentLanguage(): string {
    return this.currentLanguage.value;
  }
}
